export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export const allQuizzes: Record<number, QuizQuestion[]> = {
  1: [
    { question: 'Which OSI layer is responsible for routing packets between networks?', options: ['Layer 1 - Physical', 'Layer 2 - Data Link', 'Layer 3 - Network', 'Layer 4 - Transport'], correct: 2, explanation: 'Layer 3 (Network) handles logical addressing and routing.' },
    { question: 'What is the default subnet mask for a Class C IP address?', options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'], correct: 2, explanation: 'Class C uses /24 (255.255.255.0).' },
    { question: 'Which protocol uses port 443?', options: ['HTTP', 'HTTPS', 'FTP', 'SSH'], correct: 1, explanation: 'HTTPS uses port 443 for encrypted web traffic.' },
    { question: 'How many bits are in an IPv4 address?', options: ['32 bits', '64 bits', '128 bits', '256 bits'], correct: 0, explanation: 'IPv4 addresses are 32 bits long.' },
    { question: 'What does ARP stand for?', options: ['Address Resolution Protocol', 'Automatic Routing Protocol', 'Advanced Resource Protocol', 'Address Routing Process'], correct: 0, explanation: 'ARP maps IP addresses to MAC addresses.' },
    { question: 'Which TCP flag initiates a connection?', options: ['ACK', 'FIN', 'SYN', 'RST'], correct: 2, explanation: 'SYN flag starts the three-way handshake.' },
    { question: 'What is the private IP range for Class A?', options: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '169.254.0.0/16'], correct: 0, explanation: 'Class A private range is 10.0.0.0/8.' },
    { question: 'Which command shows IP configuration on a Cisco router?', options: ['show interfaces', 'show ip route', 'show running-config', 'show ip interface brief'], correct: 3, explanation: '"show ip interface brief" shows interface IP summary.' },
    { question: 'What is the purpose of DNS?', options: ['Assign IPs automatically', 'Resolve domain names to IPs', 'Encrypt traffic', 'Route packets'], correct: 1, explanation: 'DNS translates domain names to IP addresses.' },
    { question: 'How many usable hosts in a /26 subnet?', options: ['30', '62', '126', '254'], correct: 1, explanation: '/26 = 64 addresses - 2 = 62 usable hosts.' },
    { question: 'What is the loopback address in IPv4?', options: ['0.0.0.0', '127.0.0.1', '255.255.255.255', '192.168.0.1'], correct: 1, explanation: '127.0.0.1 is the IPv4 loopback address.' },
    { question: 'Which protocol is connectionless?', options: ['TCP', 'UDP', 'Both', 'Neither'], correct: 1, explanation: 'UDP is connectionless — no connection setup required.' },
    { question: 'What does CIDR notation /24 represent?', options: ['24 host bits', '24 network bits', '24 total bits', '24 addresses'], correct: 1, explanation: '/24 means 24 bits for the network portion.' },
    { question: 'Which OSI layer handles MAC addresses?', options: ['Layer 1', 'Layer 2', 'Layer 3', 'Layer 4'], correct: 1, explanation: 'Layer 2 (Data Link) uses MAC addresses.' },
    { question: 'What is the purpose of a default gateway?', options: ['Assign IP addresses', 'Route traffic outside local network', 'Encrypt data', 'Block viruses'], correct: 1, explanation: 'Default gateway routes traffic to other networks.' },
  ],
  2: [
    { question: 'What does a switch use to forward frames?', options: ['IP address', 'MAC address', 'Port number', 'Hostname'], correct: 1, explanation: 'Switches use MAC addresses for forwarding.' },
    { question: 'What is a VLAN?', options: ['A physical device', 'A virtual broadcast domain', 'A cable type', 'A routing protocol'], correct: 1, explanation: 'VLANs create separate broadcast domains.' },
    { question: 'Which protocol prevents Layer 2 loops?', options: ['OSPF', 'STP', 'ARP', 'DHCP'], correct: 1, explanation: 'STP prevents loops by blocking redundant paths.' },
    { question: 'What is the maximum cable run for Cat 5e UTP?', options: ['50m', '100m', '200m', '500m'], correct: 1, explanation: 'Maximum UTP cable run is 100 meters.' },
    { question: 'What does 802.1Q do?', options: ['Wireless connectivity', 'Tags frames with VLAN ID', 'Routes packets', 'Assigns IPs'], correct: 1, explanation: '802.1Q inserts a VLAN tag into frames.' },
    { question: 'What is the native VLAN by default?', options: ['VLAN 0', 'VLAN 1', 'VLAN 10', 'VLAN 100'], correct: 1, explanation: 'Default native VLAN is VLAN 1.' },
    { question: 'Which PoE standard provides up to 30W?', options: ['802.3af', '802.3at', '802.3bt', '802.3ab'], correct: 1, explanation: '802.3at (PoE+) provides up to 30W.' },
    { question: 'What does PortFast do?', options: ['Blocks the port', 'Immediately forwards', 'Shuts down port', 'Enables trunking'], correct: 1, explanation: 'PortFast immediately transitions to forwarding.' },
    { question: 'Which wireless standard operates only on 5 GHz?', options: ['802.11b', '802.11g', '802.11a', '802.11n'], correct: 2, explanation: '802.11a operates only on 5 GHz.' },
    { question: 'What is EtherChannel?', options: ['A wireless protocol', 'Bundling multiple links', 'A firewall', 'A routing algorithm'], correct: 1, explanation: 'EtherChannel bundles physical links into one logical link.' },
    { question: 'What security protocol is recommended for wireless?', options: ['WEP', 'WPA', 'WPA2', 'WPA3'], correct: 3, explanation: 'WPA3 is the most secure wireless protocol.' },
    { question: 'What is BPDU Guard used for?', options: ['Preventing loops', 'Disabling ports receiving BPDUs', 'Encrypting traffic', 'Assigning VLANs'], correct: 1, explanation: 'BPDU Guard err-disables ports that receive BPDUs.' },
    { question: 'What is the STP root bridge elected by?', options: ['Highest MAC', 'Lowest Bridge ID', 'Highest IP', 'Fastest port'], correct: 1, explanation: 'Root bridge is elected by lowest Bridge ID.' },
    { question: 'What does CSMA/CA stand for?', options: ['Collision Detection', 'Collision Avoidance', 'Carrier Access', 'Channel Management'], correct: 1, explanation: 'CSMA/CA = Carrier Sense Multiple Access with Collision Avoidance.' },
    { question: 'What is the difference between access and trunk ports?', options: ['Speed difference', 'Access = 1 VLAN, Trunk = multiple VLANs', 'No difference', 'Access is faster'], correct: 1, explanation: 'Access ports carry one VLAN; trunk ports carry multiple VLANs.' },
  ],
  3: [
    { question: 'What is the default AD of OSPF?', options: ['90', '110', '120', '170'], correct: 1, explanation: 'OSPF has a default AD of 110.' },
    { question: 'What does a floating static route use?', options: ['Same AD', 'Higher AD than primary', 'Lower AD', 'No AD'], correct: 1, explanation: 'Floating static routes have higher AD as backup.' },
    { question: 'Which command configures a default route?', options: ['ip route 0.0.0.0 0.0.0.0', 'ip default-route', 'default-route', 'route default'], correct: 0, explanation: '"ip route 0.0.0.0 0.0.0.0 next-hop" creates a default route.' },
    { question: 'What is Router-on-a-Stick?', options: ['A wireless protocol', 'Inter-VLAN routing with subinterfaces', 'A switch type', 'A routing protocol'], correct: 1, explanation: 'Router-on-a-Stick uses subinterfaces for inter-VLAN routing.' },
    { question: 'What does OSPF use to elect a DR?', options: ['Highest IP', 'Highest router ID', 'Lowest IP', 'Lowest router ID'], correct: 1, explanation: 'OSPF elects DR by highest router ID.' },
    { question: 'What is the OSPF hello timer default?', options: ['10 sec', '30 sec', '40 sec', '120 sec'], correct: 0, explanation: 'Default OSPF hello timer is 10 seconds.' },
    { question: 'What does HSRP provide?', options: ['Load balancing', 'First hop redundancy', 'Wireless', 'Encryption'], correct: 1, explanation: 'HSRP provides first hop redundancy.' },
    { question: 'Which command shows OSPF neighbors?', options: ['show ip ospf', 'show ip ospf neighbor', 'show ip route ospf', 'show ospf database'], correct: 1, explanation: '"show ip ospf neighbor" shows OSPF neighbors.' },
    { question: 'What is the longest prefix match rule?', options: ['Lowest AD wins', 'Most specific match wins', 'Lowest metric wins', 'Highest priority wins'], correct: 1, explanation: 'Most specific route (longest prefix) is selected.' },
    { question: 'What is an ABR in OSPF?', options: ['AS Border Router', 'Area Border Router', 'Active Backup Router', 'Address Broadcast Router'], correct: 1, explanation: 'ABR connects multiple OSPF areas.' },
    { question: 'What is the OSPF dead timer default?', options: ['10 sec', '30 sec', '40 sec', '120 sec'], correct: 2, explanation: 'Default OSPF dead timer is 40 seconds.' },
    { question: 'Which command enables OSPF process 1?', options: ['ospf 1', 'router ospf 1', 'enable ospf 1', 'ip ospf 1'], correct: 1, explanation: '"router ospf 1" enables OSPF process 1.' },
    { question: 'What is the OSPF neighbor state after full adjacency?', options: ['Init', '2-Way', 'ExStart', 'Full'], correct: 3, explanation: 'Full state means full adjacency established.' },
    { question: 'What does a DR do in OSPF?', options: ['Routes all traffic', 'Sends LSAs to all neighbors', 'Blocks ports', 'Assigns IPs'], correct: 1, explanation: 'DR reduces adjacencies by sending LSAs to all.' },
    { question: 'What metric does OSPF use?', options: ['Hop count', 'Bandwidth (cost)', 'Delay', 'MTU'], correct: 1, explanation: 'OSPF uses bandwidth-based cost as metric.' },
  ],
  4: [
    { question: 'What are the four DHCP messages in order?', options: ['Discover, Offer, Request, Ack', 'Request, Offer, Discover, Ack', 'Offer, Discover, Ack, Request', 'Discover, Request, Offer, Ack'], correct: 0, explanation: 'DHCP DORA: Discover, Offer, Request, Acknowledge.' },
    { question: 'What does PAT stand for?', options: ['Port Address Translation', 'Private Address Translation', 'Protocol Address Translation', 'Public Address Translation'], correct: 0, explanation: 'PAT maps multiple private IPs to one public IP using ports.' },
    { question: 'What is the syslog severity for Emergency?', options: ['0', '1', '7', '6'], correct: 0, explanation: 'Emergency is severity level 0.' },
    { question: 'Which SNMP version provides encryption?', options: ['SNMPv1', 'SNMPv2c', 'SNMPv3', 'All versions'], correct: 2, explanation: 'SNMPv3 provides authentication and encryption.' },
    { question: 'What command configures DHCP relay?', options: ['ip dhcp relay', 'ip helper-address', 'dhcp forward', 'ip dhcp forwarder'], correct: 1, explanation: '"ip helper-address" configures DHCP relay.' },
    { question: 'What is the difference between SSH and Telnet?', options: ['SSH is faster', 'SSH encrypts traffic', 'Telnet uses different ports', 'No difference'], correct: 1, explanation: 'SSH encrypts traffic; Telnet sends in clear text.' },
    { question: 'What does NTP synchronize?', options: ['IP addresses', 'Clocks/time', 'Routing tables', 'VLAN databases'], correct: 1, explanation: 'NTP synchronizes clocks across devices.' },
    { question: 'What QoS marking is used at Layer 3?', options: ['CoS', 'DSCP', '802.1p', 'MPLS'], correct: 1, explanation: 'DSCP is used at Layer 3 for QoS.' },
    { question: 'Which command enables SSH on a Cisco router?', options: ['ssh enable', 'crypto key generate rsa', 'ip ssh enable', 'ssh server enable'], correct: 1, explanation: '"crypto key generate rsa" generates RSA keys for SSH.' },
    { question: 'What does NAT overload configure?', options: ['Static NAT', 'Dynamic NAT', 'PAT', 'No NAT'], correct: 2, explanation: 'NAT overload configures PAT.' },
    { question: 'What is the DHCP lease renewal process?', options: ['T1 at 50%, T2 at 87.5%', 'T1 at 87.5%, T2 at 50%', 'Automatic', 'Manual only'], correct: 0, explanation: 'T1 at 50% renews with original server; T2 at 87.5% broadcasts.' },
    { question: 'What port does DNS use?', options: ['21', '23', '53', '80'], correct: 2, explanation: 'DNS uses port 53 (TCP and UDP).' },
    { question: 'What is inside local in NAT?', options: ['Public IP before translation', 'Private IP before translation', 'Public IP after translation', 'Private IP after translation'], correct: 1, explanation: 'Inside local is the private IP before NAT translation.' },
    { question: 'What does syslog severity 3 mean?', options: ['Emergency', 'Critical', 'Error', 'Warning'], correct: 2, explanation: 'Severity 3 = Error condition.' },
    { question: 'What is the purpose of NTP stratum?', options: ['Security level', 'Distance from reference clock', 'Speed rating', 'Priority level'], correct: 1, explanation: 'Stratum indicates hops from the reference clock.' },
  ],
  5: [
    { question: 'What does an ACL use to match packets?', options: ['MAC addresses only', 'Access control entries', 'VLAN tags', 'Port numbers only'], correct: 1, explanation: 'ACLs use ACEs to match traffic.' },
    { question: 'What is the implicit rule at the end of every ACL?', options: ['Permit all', 'Deny all', 'Log all', 'Forward all'], correct: 1, explanation: 'Every ACL has implicit deny all at the end.' },
    { question: 'Which ACL type filters based on source IP?', options: ['Extended ACL', 'Standard ACL', 'Named ACL', 'Reflexive ACL'], correct: 1, explanation: 'Standard ACLs filter by source IP only.' },
    { question: 'What does port security "shutdown" mode do?', options: ['Drops frames', 'Drops and logs', 'Shuts down the port', 'Allows all traffic'], correct: 2, explanation: 'Shutdown mode err-disables the port.' },
    { question: 'What does AAA stand for?', options: ['Authentication, Authorization, Accounting', 'Access, Authentication, Authorization', 'Authentication, Access, Accounting', 'Authorization, Access, Authentication'], correct: 0, explanation: 'AAA = Authentication, Authorization, Accounting.' },
    { question: 'What protocol does 802.1X use?', options: ['SSH', 'HTTPS', 'RADIUS', 'SNMP'], correct: 2, explanation: '802.1X uses RADIUS for authentication.' },
    { question: 'What is DHCP snooping?', options: ['Monitoring DHCP', 'Blocking unauthorized DHCP servers', 'Encrypting DHCP', 'Speeding up DHCP'], correct: 1, explanation: 'DHCP snooping blocks unauthorized DHCP servers.' },
    { question: 'Which VPN type connects two sites permanently?', options: ['Remote access', 'Site-to-site', 'SSL VPN', 'Client VPN'], correct: 1, explanation: 'Site-to-site VPNs create permanent tunnels.' },
    { question: 'What does IPSec ESP provide?', options: ['Auth only', 'Encryption only', 'Auth and encryption', 'Neither'], correct: 2, explanation: 'ESP provides both authentication and encryption.' },
    { question: 'What is a wildcard mask of 0.0.0.255?', options: ['/8', '/16', '/24', '/32'], correct: 2, explanation: 'Wildcard 0.0.0.255 = /24 subnet mask.' },
    { question: 'What is the difference between standard and extended ACLs?', options: ['No difference', 'Standard = source only, Extended = source+dest+protocol', 'Extended is older', 'Standard is more secure'], correct: 1, explanation: 'Extended ACLs can match on source, destination, protocol, and port.' },
    { question: 'Where should extended ACLs be placed?', options: ['Near destination', 'Near source', 'In the middle', 'Anywhere'], correct: 1, explanation: 'Extended ACLs should be placed as close to the source as possible.' },
    { question: 'What is Dynamic ARP Inspection?', options: ['Monitoring ARP traffic', 'Validating ARP against DHCP snooping table', 'Blocking all ARP', 'Encrypting ARP'], correct: 1, explanation: 'DAI validates ARP packets against the DHCP snooping binding table.' },
    { question: 'What is a zone-based firewall?', options: ['A physical device', 'Traffic filtering between security zones', 'A VPN type', 'A routing protocol'], correct: 1, explanation: 'ZBF filters traffic between defined security zones.' },
    { question: 'What is the purpose of port security?', options: ['Speed optimization', 'Limit MAC addresses per port', 'Encrypt traffic', 'Route packets'], correct: 1, explanation: 'Port security limits which MAC addresses can use a port.' },
  ],
  6: [
    { question: 'What does SDN separate?', options: ['Hardware and software', 'Control and data plane', 'LAN and WAN', 'IPv4 and IPv6'], correct: 1, explanation: 'SDN separates control plane from data plane.' },
    { question: 'Which HTTP method creates a resource?', options: ['GET', 'POST', 'PUT', 'DELETE'], correct: 1, explanation: 'POST creates a new resource.' },
    { question: 'What format do REST APIs commonly use?', options: ['XML only', 'JSON only', 'Both JSON and XML', 'HTML'], correct: 2, explanation: 'REST APIs support both JSON and XML.' },
    { question: 'What is Ansible?', options: ['A programming language', 'An agentless config management tool', 'A routing protocol', 'A firewall'], correct: 1, explanation: 'Ansible is agentless automation using SSH.' },
    { question: 'What does NETCONF use for data modeling?', options: ['JSON', 'XML', 'YANG', 'HTML'], correct: 2, explanation: 'NETCONF uses YANG for data modeling.' },
    { question: 'What HTTP status code means "Not Found"?', options: ['200', '400', '401', '404'], correct: 3, explanation: '404 = Not Found.' },
    { question: 'What is Cisco DNA Center?', options: ['A firewall', 'An intent-based networking platform', 'A routing protocol', 'A cable type'], correct: 1, explanation: 'DNA Center is an intent-based networking platform.' },
    { question: 'What does RESTCONF use for communication?', options: ['SSH', 'Telnet', 'HTTP/HTTPS', 'SNMP'], correct: 2, explanation: 'RESTCONF uses HTTP/HTTPS methods.' },
    { question: 'Which tool is agent-based?', options: ['Ansible', 'Puppet', 'Both', 'Neither'], correct: 1, explanation: 'Puppet is agent-based; Ansible is agentless.' },
    { question: 'What is YANG used for?', options: ['Routing', 'Data modeling for network config', 'Wireless security', 'Cable management'], correct: 1, explanation: 'YANG is a data modeling language for network devices.' },
    { question: 'What does the SDN controller do?', options: ['Forwards packets', 'Makes all control plane decisions', 'Cables management', 'Wireless access'], correct: 1, explanation: 'SDN controller centralizes control plane decisions.' },
    { question: 'What is the difference between GET and POST?', options: ['No difference', 'GET reads, POST creates', 'POST is faster', 'GET is more secure'], correct: 1, explanation: 'GET retrieves data; POST creates new resources.' },
    { question: 'What is NETCONF?', options: ['A firewall', 'Network configuration protocol', 'A routing algorithm', 'A wireless standard'], correct: 1, explanation: 'NETCONF is a protocol for network device configuration.' },
    { question: 'What does CRUD stand for?', options: ['Copy, Read, Update, Delete', 'Create, Read, Update, Delete', 'Create, Route, Update, Deploy', 'Copy, Route, Upload, Download'], correct: 1, explanation: 'CRUD = Create, Read, Update, Delete.' },
    { question: 'What is the purpose of YANG models?', options: ['Wireless security', 'Define configuration and state data', 'Cable management', 'Power delivery'], correct: 1, explanation: 'YANG models define how network devices are configured and monitored.' },
  ],
};
